### ISSUE TITLE
setVocAlgorithmState Example

### ISSUE THREAD

**Issue by protttoy** [Sensirion/arduino-i2c-sen5x#11]
I am trying to get the voc algorithm state and set it upon startup.

For getting the algorithm array
```
byte statesize = 12;
byte state[statesize];
int error = sen5x.getVocAlgorithmState(state,statesize);
```

> Output : { 49, 229, 238, 62, 0, 49, 202, 99, 185, 252, 63, 123 }

After that when saving the state, "**Not enough space in buffer**" error triggers for the following code:

```
byte statesize = 12;
byte state[statesize] = { 49, 229, 238, 62, 0, 49, 202, 99, 185, 252, 63, 123 };
char errorMessage[256];
int error = sen5x.setVocAlgorithmState(state,statesize);
if(error)
{
    errorToString(error, errorMessage, 256);
    Serial.println(errorMessage);
}
```

The error occurs from the `Sensirion Arduino Core --> SensirionI2CTxFrame.cpp --> uint16_t SensirionI2CTxFrame::_addByte(uint8_t data)` function. 

SEN5x datasheet says in section 6.1.11 that there is Checksum returned when reading. Do I not send the checksum when using the setVocAlgorithmState ? An example of how to set the state would be really appreciated. Thank you

**Comment by Rol-la** [comment]
On what hardware are you working? 
On some Arduinos the i2c communication buffer is not large enough to transmit the fully assembled data frame. 
The checksum computation is implemented in the Sensirion Software library and you should not need to deal with it.

**Comment by protttoy** [comment]
@Rol-la , I am using ESP32. I can confirm that this is not an issue of i2c buffer size, I have tried increasing the size.

The main issue is that, when I read the states with `getVocAlgorithmState` it returns 12 values. according to datasheet the 3rd, 6th, 9th and 12th value are checksum. Upon closer inspection of 

`Sensirion Arduino Core --> SensirionI2CTxFrame.cpp --> SensirionI2CTxFrame::_addByte`

 it calculates the checksum itself, so the input of the `setVocAlgorithmState` should take only 8 (12 - 4 checksum) values ? The error does not trigger with 8 values.

Can you please tell me if the following code is the correct approach for saving the VOC state ? if the `getVocAlgorithmState `output is `{ 49, 229, 238, 62, 0, 49, 202, 99, 185, 252, 63, 123 }`

```
byte statesize = 8;
byte state[statesize] = { 49, 229, 62, 0, 202, 99 , 252, 63};
char errorMessage[256];
int error = sen5x.setVocAlgorithmState(state,statesize);
if(error)
{
    errorToString(error, errorMessage, 256);
    Serial.println(errorMessage);
}
```

**Comment by Rol-la** [comment]
Hello,
It is as you write: The VocAlgorithmState must have exactly 8 bytes (https://sensirion.com/media/documents/6791EFA0/62A1F68F/Sensirion_Datasheet_Environmental_Node_SEN5x.pdf).
A checksum is inserted every third byte => byte [0,1] is data, byte[2] is checksum, byte [3,4] is data and byte [5] is checksum ..
So you code snippet with 8 bytes in the state variable is correct.

**Comment by protttoy** [comment]
@Rol-la Thanks a lot !!
