### ISSUE TITLE
Incorrect 'typicalParticleSize' returned from 'readMeasuredPmValues'

### ISSUE THREAD

**Issue by Bitwise-Systems** [Sensirion/arduino-i2c-sen5x#2]
The header file for the library notes that 'typicalParticleSize' as returned by 'readMeasuredPmValuesAsIntegers' needs to be scaled, by dividing by 1000, to produce the floating point size in microns as returned by 'readMeasuredPmValues'. The code only divides by 10. Boulders!

**Comment by psachs** [comment]
Thank you for pointing out our error. We fixed it in master an will release a new version soon
