### ISSUE TITLE
Scaled by ten values don't show as scaled by ten in comment examples

### ISSUE THREAD

**Issue by tyeth** [Sensirion/arduino-i2c-sen5x#3]
Look towards the end of this comment and you'll see that one of the particle values is correctly shown as scaled by 10, but the rest are not, and I've highlighted the first incorrect line in the comment.
https://github.com/Sensirion/arduino-i2c-sen5x/blob/d7a73c86073cca34b84cde83814f5c17b87aad6d/src/SensirionI2CSen5x.h#L337

**Comment by tyeth** [comment]
Sorry I'm using this for reference but the repo I'm actually working in is the raspberry pi one https://github.com/Sensirion/raspberry-pi-i2c-sen5x

**Comment by psachs** [comment]
Thanks for reporting, this is a bug in the documentation. We will fix this in a future version

**Comment by LeonieFierz** [comment]
We just published a new version 0.3.0 of the Arduino driver updating the comments. In Raspberry Pi Driver we found no incorrect comments.
